export const THEATER_OPTIONS_FETCH = 'THEATER_OPTIONS_FETCH';
export const THEATER_OPTIONS_RESULT = 'THEATER_OPTIONS_RESULT';
export const THEATER_OPTIONS_ERROR = 'THEATER_OPTIONS_ERROR';

export const MOVIE_OPTIONS_FETCH = 'MOVIE_OPTIONS_FETCH';
export const MOVIE_OPTIONS_RESULT = 'MOVIE_OPTIONS_RESULT';
export const MOVIE_OPTIONS_ERROR = 'MOVIE_OPTIONS_ERROR';

export const THEATER_DETAILS_FETCH = 'THEATER_DETAILS_FETCH';
export const THEATER_DETAILS_RESULT = 'THEATER_DETAILS_RESULT';
export const THEATER_DETAILS_ERROR = 'THEATER_DETAILS_ERROR';

export const MOVIE_DETAILS_FETCH = 'MOVIE_DETAILS_FETCH';
export const MOVIE_DETAILS_RESULT = 'MOVIE_DETAILS_RESULT';
export const MOVIE_DETAILS_ERROR = 'MOVIE_DETAILS_ERROR';
