export const OPTIONS_FETCH = 'OPTIONS_FETCH';
export const OPTIONS_RESULT = 'OPTIONS_RESULT';
export const OPTIONS_ERROR = 'OPTIONS_ERROR';

export const THEATER_DETAILS_FETCH = 'THEATER_DETAILS';
export const THEATER_DETAILS_RESULT = 'THEATER_DETAILS_RESULT';
export const THEATER_DETAILS_ERROR = 'THEATER_DETAILS_ERROR';

export const MOVIE_DETAILS_FETCH = 'MOVIE_DETAILS_FETCH';
export const MOVIE_DETAILS_RESULT = 'MOVIE_DETAILS_RESULT';
export const MOVIE_DETAILS_ERROR = 'MOVIE_DETAILS_ERROR';
